# Staging Docker Compose Configuration
# This file overrides settings for staging deployment

version: '3.8'

services:
  postgres:
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-teacher_hub_staging}
      POSTGRES_USER: ${POSTGRES_USER:-teacher_hub_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data

  redis:
    volumes:
      - redis_staging_data:/data

  elasticsearch:
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_staging_data:/usr/share/elasticsearch/data

  backend:
    environment:
      NODE_ENV: staging
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      JWT_SECRET: ${JWT_SECRET}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      YOUTUBE_CLIENT_ID: ${YOUTUBE_CLIENT_ID}
      YOUTUBE_CLIENT_SECRET: ${YOUTUBE_CLIENT_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      CLAMAV_HOST: clamav
      ENABLE_VIRUS_SCANNING: "true"
      ENABLE_CONTENT_SCANNING: "true"
      SENTRY_DSN: ${SENTRY_DSN}
      LOG_LEVEL: debug
      PORT: 3001
    command: npm start

  web:
    environment:
      VITE_API_URL: ${API_URL:-https://staging-api.teacherhub.ug}
      VITE_WS_URL: ${WS_URL:-wss://staging-api.teacherhub.ug}
      NODE_ENV: staging

volumes:
  postgres_staging_data:
  redis_staging_data:
  elasticsearch_staging_data: